language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - wget https://github.com/jgm/pandoc/releases/download/2.5/pandoc-2.5-1-amd64.deb
  - sudo dpkg -i pandoc-2.5-1-amd64.deb
  - pandoc -v
install:
  - pip install coveralls
  - pip install tox-travis
script:
  - tox
  - pip install pip2
  - pip install pip3
  - pip2 install coverage
  - pip3 install coverage
  - python2 -m coverage run -a --source=pandoc_codeblock_include setup.py test
  - python3 -m coverage run -a --source=pandoc_codeblock_include setup.py test
  - coverage report -m
after_success:
  - coveralls
