language: generic
before_install:
  - wget https://github.com/jgm/pandoc/releases/download/2.5/pandoc-2.5-1-amd64.deb
  - sudo dpkg -i pandoc-2.5-1-amd64.deb
  - pandoc -v
  - sudo apt-get install python2.7
  - sudo apt-get install python
  - sudo apt-get install python-pip
  - pip install --user --upgrade pip
install:
  - pip install coveralls
  - pip install tox-travis
script:
  - tox
  - coverage report -m
after_success:
  - coveralls
